name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kyoungholee/docker-example:latest
          platforms: linux/amd64
          build-args: |
            NEXT_PUBLIC_API_URL=http://192.168.0.22:8080/api/v1

      # - name: SSH to EC2 and deploy
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_FRONT_PEM_KEY }}
      #     script: |
      #       docker pull kyoungholee/docker-example:latest
      #       docker stop erp-next-front || true
      #       docker rm erp-next-front || true
      #       docker run -d -p 80:3000 --name erp-next-front kyoungholee/docker-example:latest
