name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kyoungholee/docker-example:latest
          platforms: linux/amd64
          build-args: |
            NEXT_PUBLIC_API_URL=https://dev-erp-api.dooson.it/api/v1

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_FRONT_PEM_KEY }}
          script: |
            # 새 컨테이너 이름과 포트
            NEW_CONTAINER="erp-next-front-$(date +%s)"
            NEW_PORT=3001

            # Docker 이미지 최신화
            docker pull kyoungholee/docker-example:latest

            # 새 컨테이너 실행 (기존 서비스 중단 없이)
            docker run -d --restart=always -p $NEW_PORT:3000 --name $NEW_CONTAINER kyoungholee/docker-example:latest

            # Nginx upstream 파일 경로
            UPSTREAM_CONF="/etc/nginx/conf.d/erp_upstream.conf"

            # 새 컨테이너로 upstream 변경
            echo "upstream erp_frontend { server 127.0.0.1:$NEW_PORT; }" > $UPSTREAM_CONF

            # Nginx reload
            nginx -s reload

            # 기존 컨테이너 중지 및 삭제
            EXISTING=$(docker ps -q -f name=erp-next-front)
            if [ -n "$EXISTING" ]; then
              docker stop $EXISTING
              docker rm $EXISTING
            fi
